import type { Metadata } from "next";
import { Fira_Code, Josefin_Sans } from "next/font/google";
import "./globals.css";
import ApolloWrapper from "@/components/ApolloWrapper";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-josefin",
});

const geistMono = Fira_Code({
  variable: "--font-firacode",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloWrapper>
          <Header />
          <Navbar />
          <main className="p-4">{children}</main>
          <Footer />
        </ApolloWrapper>
      </body>
    </html>
  );
}
